services:
  equicloud:
    image: ghcr.io/equicord/equicloud:latest
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      scylla:
        condition: service_healthy
    restart: unless-stopped

  scylla:
    image: scylladb/scylla:2025.3.1
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./scylla_data:/var/lib/scylla
    command: [
      "--smp=2",
      "--memory=4G"
    ]
    environment:
      - SCYLLA_ARGS=--log-to-stdout=1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 20s
      timeout: 10s
      retries: 5


volumes:
  scylla_data: