services:
  equicloud:
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      scylla:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - equicloud_net

  scylla:
    image: scylladb/scylla:2025.3.1
    container_name: scylla-node
    restart: unless-stopped
    volumes:
      - scylla_data:/var/lib/scylla
    command: [
      "--smp=2",
      "--memory=4G"
    ]
    environment:
      - SCYLLA_ARGS=--log-to-stdout=1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - equicloud_net


volumes:
  scylla_data:

networks:
  equicloud_net:
    driver: bridge